### ISSUE TITLE
umqtt last will is not sent

### ISSUE THREAD

**Issue by RichardMore** [micropython/micropython-lib#304] opened 2018-08-27 18:21 UTC
Last will message is not sent when Nodemcu loses power.

Code:
```
client = MQTTClient(client_id=MQTT_CLIENT, server=MQTT_SERVER, port=MQTT_PORT, user=MQTT_USER, password=MQTT_PASS)
client.set_last_will('status', 'disconnected', retain=True)
client.set_callback(sub_cb)
client.connect()
client.subscribe(MQTT_ROOT + '#')
mqtt_publish('status', 'connected', retain=True)
```

The "connected" message is delivered after connection and topic subscribe, but no "disconnected" message ever.

**Comment by SpotlightKid** [comment] 2018-08-28 12:30
I can't reproduce this, i.e. works perfectly here.

Which MQTT broker are you using and which MQTT client do you have subscribed to the `status`topic to receive the last will message? Have you checked the broker server logs?

It is the responsibility of the server to publish the last will message and of course only clients subscribed (in your example) to the `status` topic will receive it. Depending on what value `MQTT_ROOT` has, your client code above does not subscribe to this topic, so it will not receive the `disconnected` messages on re-connect, even if `retain=True` is set for the last will.

For reference, here's the code, with which I tested this. If `MQTT_ROOT` is changed to `''` (empty string), this client will receive messages to the `status` topic and so, on re-connect, will receive its own last will message from the previous disconnect.

```
from umqtt.simple import MQTTClient

MQTT_CLIENT = 'upy'
MQTT_SERVER = '127.0.0.1'
MQTT_ROOT = '/'

def sub_cb(topic, msg):
    print((topic, msg))

client = MQTTClient(client_id=MQTT_CLIENT, server=MQTT_SERVER)
client.set_last_will('status', 'disconnected', retain=True)
client.set_callback(sub_cb)
client.connect()
client.subscribe(MQTT_ROOT + '#')
```
client.publish('status', 'connected', retain=True)

try:
    while True:
        client.wait_msg()
except KeyboardInterrupt:
    pass

**Comment by RichardMore** [comment] 2018-08-28 18:05
I am using the public Cloudmqtt and I am checking the messages through the websocket UI which shows every topic. Just as a side note, a Ubutntu based server that has a mosquitto service attached to it has a las will as well and I receive those, so probably the broker side is good from Cloudmqtt.
Here is my full code I am testing with:

```
from umqtt.simple import MQTTClient
import wifi

# init program
wifi.do_connect()

MQTT_SERVER = 'm21.cloudmqtt.com'
MQTT_PORT = <PORT>
MQTT_USER = <USER>
MQTT_PASS = <PASSWORD>
MQTT_TIMEOUT = 30
MQTT_CLIENT = <ID>
MQTT_ROOT = <ROOT>

client = None
topic_l1 = 'sensors/'

# helper methods
def mqtt_publish(topic_l2, payload, retain=False, qos=0):
	client.publish(MQTT_ROOT + topic_l1 + topic_l2, payload, retain, 0)
	print('mqtt published msg: %s; to topic: %s' % (payload, MQTT_ROOT + topic_l1 + topic_l2))

def sub_cb(topic, msg):
	print('got msg')

client = MQTTClient(client_id=MQTT_CLIENT, server=MQTT_SERVER, port=MQTT_PORT, user=MQTT_USER, password=MQTT_PASS)
client.set_last_will('status', 'disconnected', retain=True)
client.set_callback(sub_cb)
client.connect()
client.subscribe(MQTT_ROOT + '#')
print('mqtt connected to %s, subscribed to %s topic' % (MQTT_SERVER, MQTT_ROOT))
mqtt_publish('status', 'connected', retain=True)

try:
	while True:
		client.wait_msg()
except KeyboardInterrupt:
	pass

```
Also I am running the code on a NodeMCU ESP8266 board.

Thank you.

**Comment by SpotlightKid** [comment] 2018-08-28 21:58
> I am using the public Cloudmqtt and I am checking the messages through the websocket UI which shows every topic. Just as a side note, a Ubutntu based server that has a mosquitto service attached to it has a las will as well and I receive those, so probably the broker side is good from Cloudmqtt.

I don't follow. If it works with the mosquito server (with which I tested it successfully as well), but not with Cloumqtt, my guess would be that Cloudmqtt is to blame.

> Also I am running the code on a NodeMCU ESP8266 board.

I've only tested it with the micropython unix port so far, but knowing the `umqtt.simple` code very well, I don't see were this would make any difference. If the client sends the last will topic and message successfully ib connecting to the broker, everything else is up to the broker.

**Comment by SpotlightKid** [comment] 2018-09-13 19:36
There was a dicsussion o nthis topic at the forum here:

**Comment by jonnor** [comment] 2024-08-25 11:35
Setting keepalive seems to avoid this problem. Proposing to close this issue.

**Comment by projectgus** [comment] 2024-08-27 02:13
> Setting keepalive seems to avoid this problem. Proposing to close this issue.

Note also this refers to a keepalive timeout on the server. Reliable last will delivery depends on the server noticing the client has gone away.

**Closed by projectgus** 2024-08-27 02:13 UTC
